### PR TITLE
Add '--stdin' option for piping output directly into jsxhint.

### PR DESCRIPTION
**Pull request by STRML**
I'm building a sublimelinter-jsxhint plugin and I needed this feature to pipe buffer contents directly into the tool.

### CODE REVIEW

**Comment by toddself** [comment]
Would love to see some tests using the streams interface added to the test suite before I merge this.

Other than that it looks good!

**Comment by STRML** [comment]
Yeah that's a good idea. I'd like to add a test comparing the output to jshint as well in order to ensure parity so that jsxhint can be used as a stable substitute for arbitrary tooling in React projects. I'll commit a few in the next few days as I have time.

**Comment by toddself** [comment]
Awesome. I'll gladly accept snything that provides for test coverage

**Comment by STRML** [comment]
Going to close this as #9 fixes the actual problem. [SublimeLinter/SublimeLinter-jsxhint](https://github.com/SublimeLinter/SublimeLinter-jsxhint) uses #9.

**Comment by toddself** [comment]
@STRML you want jsxhint on npm?  You can have it.  I was about to publish the latest version using mutiny, but noticed JSHint allows for ignore comments and specifically refers to React when mentioning.  I feel like using ignores around JSX syntax is the appropriate way forward and am closing this project.

**Pull request closed without merging**
