### PR TITLE
Rewrite to proxy JSHint options & output.

### PR DESCRIPTION
**Pull request by STRML**
After working with jsxhint for a while I felt that it could be improved by delegating more of its function to JSHint, rather than providing its own globbing / ignore mechanism.

I figured that in most cases, users will want to use `jsxhint` as a transparent alternative to `jshint`, expecting the same command-line switches & output. It should 'just work' with any libraries that expect `jshint`.

I considered creating a separate repo for this - and I will if you don't want to merge - but since CondeNast controls the `jsxhint` name on npm I figured it best to try to have this accepted as a pull rather than introduce confusion by adding something like `jsxhint2` to npm.

If you are willing to cede the name `jsxhint` on npm please let me know and I would be happy to create a new repo and maintain it.

### CODE REVIEW

**Comment by toddself** [comment]
Funny, I too was thinking about this over the past couple of days.  I've been re-writing it so it works more like browserify using a tool called [mutiny](/thlorenz/mutiny)

I just pushed up my changes to a new branch (still a WIP), but the basic concept is that you can apply a series of transforms on the input and then run JSHint (with all of JSHint's command line syntax and interface preserved) on those transformed inputs.

I feel this is a much more extendable and modular way to support the pre-translation of assets before sending them through the linter.

**Comment by STRML** [comment]
It's up to you if you want to use this PR - but I think it's a pretty clean solution given that we don't really need anything particularly extensible here. `jsxhint` has one job - run jsx through react-tools and lint it, while giving no impression to the user (or other tools) that anything has happened. This branch does exactly that in ~150 LOC with few dependencies. It has a few tests written & passing to ensure the output exactly matches jshint so it can be used with existing tools that expect jshint.

I went through the mutiny rewrite; it looks like it's still not reporting results, and it needs (at least) some code to transform reporter output so it doesn't print tmp file locations. I hope you'll consider using this branch as it is already complete and working.

**Comment by thomasboyt** [comment]
:+1: to this. I _love_ that this is exactly API compatible with JSHint because that means you can modify JSHint plugins for editors to be compatible with JSXHint. I just wrote a quick [Syntastic](https://github.com/scrooloose/syntastic) plugin that literally just does a find/replace (jshint->jsxhint) on the [JSHint plugin](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/javascript/jshint.vim) and it works perfectly with this PR.

**Comment by STRML** [comment]
Thanks. Looks like the development on the `mutiny` branch has stalled. This branch is ready to go. [SublimeLinter-jsxhint](https://github.com/STRML/SublimeLinter-jsxhint) depends on it and for now will just require an `npm install -g STRML/JSXHint`.

**Comment by toddself** [comment]
@STRML the progress has not stalled.  It has just been christmas and new years and my second kid just turned 4 weeks old, so things are a little busy.  The mutiny re-write should be finished shortly.

**Comment by STRML** [comment]
Sorry, couldn't wait any longer - [SublimeLinter/SublimeLinter-jsxhint](https://github.com/SublimeLinter/SublimeLinter-jsxhint) is now published and in package control. Judging by the speed of comments on the JSXHint fork, it looks like a lot of people have started using it.

Please consider merging so we can clear up the confusion during the SublimeLinter-JSXHint installation process. If you are not willing to, please consider ceding the `jsxhint` name on npm as there has been some confusion.

**Comment by STRML** [comment]
After forking the project, @toddself has given up the name on npm - the name `jsxhint` on npm now refers to STRML/JSXHint. This PR is no longer needed. Thanks Todd.

**Pull request closed without merging**
