### PR TITLE
Transform *.jsx files

### PR DESCRIPTION
**Pull request by andreypopp**
I use `.jsx` file extension when I write JSX so I don't have to put `@jsx` pragmas everywhere. `reactify` (browserify transform for JSX) supports that and, I think, it would be very useful if `jsxhint` does this too.

### CODE REVIEW

**Comment by toddself** [comment]
Thank you for this! I just had my second kid yesterday so I can't merge until later this week :)

On Dec 2, 2013, at 6:44 PM, "Andrey Popp" <notifications@github.com<mailto:notifications@github.com>> wrote:

I use .jsx file extension when I write JSX so I don't have to put @jsx pragmas everywhere. reactify (browserify transform for JSX) supports that and, I think, it would be very useful if jsxhint does this too.

---

You can merge this Pull Request by running

  git pull https://github.com/andreypopp/JSXHint master

Or view, comment on, or merge it at:

  https://github.com/CondeNast/JSXHint/pull/3

Commit Summary
-   Transform *.jsx files

File Changes
-   M jsxhint.jshttps://github.com/CondeNast/JSXHint/pull/3/files#diff-0 (12)

Patch Links:
-   https://github.com/CondeNast/JSXHint/pull/3.patch
-   https://github.com/CondeNast/JSXHint/pull/3.diff

**Comment by andreypopp** [comment]
> Thank you for this! I just had my second kid yesterday so I can't merge until later this week :)

Congrats!

**Comment by toddself** [comment]
Awesome man! Thanks for the change.  And thanks for the congrats :)

**Comment by andreypopp** [comment]
Cool, can we have a new version released then?

**Comment by toddself** [comment]
v0.2.0 is now pushed to npm and published to github!

**Pull request merged**
